apiVersion: v1
kind: LimitRange
metadata:
  name: default-requests-limits
  namespace: development
spec:
  limits:
  - default:
      memory: 1Gi
      cpu: 1
    defaultRequest:
      memory: 500Mi
      cpu: 0.5
    type: Container
